config/routes.rb
Rails.application.routes.draw do
  resources :promos
  resources :line_items do 
    collection do
      put 'update-multiple', to: 'line_items#update_multiple', as: :update_multiple
    end
  end

  get 'page/:id', to: 'pages#front_show', as: :front_show

  scope '/admin' do
    resources :categories, :tags, :products, :years, :brands, :carts, :cars, :car_brands, :pages

    resources :charges do 
      put 'send-number', to: 'charges#send_number'
    end

    delete 'galleries/:id', to: 'galleries#destroy', as: :delete_gallerie

  end

  devise_for :users

  root 'front#index'
  get 'products/:id', to: 'front#show_product', as: :show_product
  get 'search', to: 'front#search_result', as: :search_result

  post 'products/:product_id/like', to: 'products/likes#create', as: :increase_like
  delete 'products/:product_id/like', to: 'products/likes#destroy', as: :destroy_like

  get 'cart-resume', to: 'charges#cart_resume', as: :cart_resume
  post 'charge/new', to: 'charges#credit', as: :credit_pay

  get 'charge/new-credit-direct', to: 'charges#credit_1', as: :credit_1
  get 'charge/new-credit-direct-3', to: 'charges#credit_2', as: :credit_2
  get 'charge/new-credit-direct-6', to: 'charges#credit_3', as: :credit_3

  get 'charge/new-oxxo', to: 'charges#oxxo', as: :oxxo
  post 'charge/new-oxxo/pay', to: 'charges#oxxo_pay', as: :oxxo_pay

  get 'charge/show/:id', to: 'charges#show_charge', as: :show_charge

  post 'charge/new-1', to: 'charges#create_1', as: :charge_1
  post 'charge/new-2', to: 'charges#create_2', as: :charge_2
  post 'charge/new-3', to: 'charges#create_3', as: :charge_3

  get "admin", to: 'charges#index'

  get "admin/users/defaults-users" => 'admin#n_users', as: :n_users
  get "admin/users/admins-users" => 'admin#a_users', as: :a_users

  get "admin/user/new" => 'admin#new_user', as: :new_user
  post "admin/user" => 'admin#create_user'

  get "admin/user/:id" => 'admin#show_user', as: :admin_show_user

  get "admin/user/:id/edit" => 'admin#edit', as: :user_edit
  delete "admin/user/:id" => 'admin#destroy_user', as: :user_delete

  patch "admin/user/:id" => 'admin#update'
  put "admin/user/:id" => 'admin#update', as: :user_edit_s

  get 'tags/:tag', to: 'front#search_result', as: :tag_search
  get 'brand/:brand', to: 'front#brand_search', as: :brand_search

  get 'tires', to: 'front#tires', as: :tires
  get 'auto-parts', to: 'front#auto_parts', as: :auto_parts
  get 'suspensions', to: 'front#suspensions', as: :suspensions
  get 'offers', to: 'front#offers', as: :offers

end

app/controllers/front_controller.rb
class FrontController < ApplicationController
  before_action :set_product, only: [:show_product]
  # skip_before_action :authenticate_user!, only: [:index, :show_product]
  skip_before_action :authenticate_user!

  def index
  	@st = Product.ransack(params[:q])
    # @c = Car.ransack(params[:q])
    @products = @st.result(distinct: true).published.limit(16)
    @featured = Product.featured
    @auto_parts = Product.category_is('refaccion').limit(16)
    @suspensions = Product.category_is('suspension').limit(16)
    @promos = Promo.all
  end

  def search_result
    @body_class = 'catalog'
  	if params[:tag]
      @products = Product.tagged_with(params[:tag]).published.paginate(per_page: POSTS_PER_PAGE, page: params[:page])

  	end

    @st = Product.ransack(params[:q])
    @products = @st.result(distinct: true).car_search.paginate(per_page: POSTS_PER_PAGE, page: params[:page])
  end

  def brand_search
    @body_class = 'catalog'
    
  	if params[:brand]
  		@products = Product.brand_search(params[:brand]).published.paginate(per_page: POSTS_PER_PAGE, page: params[:page])
  	end
  end

  def show_product
  	@body_class = 'show'
  	@line_item = LineItem.new

    # @folder = MEGA.root.folders[1]
    # @file = @folder.files.first
  end


  # category views
  def tires
    # to do
    @products = Product.category_is('llanta').paginate(per_page: POSTS_PER_PAGE, page: params[:page])
    @body_class = 'catalog'
  end
  def auto_parts
    # to do
    @products = Product.category_is('refaccion').paginate(per_page: POSTS_PER_PAGE, page: params[:page])
    @body_class = 'catalog'

  end
  def suspensions
    # to do
    @products = Product.category_is('suspension').paginate(per_page: POSTS_PER_PAGE, page: params[:page])
    @body_class = 'catalog'

  end

  def offers
    @offers = Product.featured
    @body_class = 'catalog'

  end



  private
  	def set_product
  		@product = Product.find(params[:id])
  	end
end

app/helpers/front_helper.rb
module FrontHelper
end

app/views/front/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = '<%= DISQUS_SHORTNAME %>' ; // required: replace example with your forum shortname
    // var disqus_identifier = 'a unique identifier for each page where Disqus is present';
    var disqus_title = '<%= title %>';
    var disqus_url = '<%= url %>';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/front/auto_parts.html.erb
<%= render 'shared/navigation' %>

<div class="container-2">
	<div class="row">
		
		<div class="col s12">
			<div class="col s12 head">
				<h5 class="b">Refacciones</h5>	
			</div>	
			<% @products.each do |product| %>
				<div class="col s12 m12 l6">
					<div class="d-1 <%= cycle('odd', 'even') %>">

						<div class="cont-tire hoverable">
								<div class="d-2">
									<% if product.brand %>
										<div class="brand">
											<%= link_to brand_search_path(product.brand.name) do %>
												<h4 class="y">
													<%= product.brand.name.upcase %>
												</h4>
											<% end %>
										</div>
									<% end %>
									<div class="title">
										<%= link_to show_product_url(product) do %>
											<h2>
												<%= product.title.upcase %>
											</h2>
										<% end %>
									</div>
									<div class="sizes">
										
									</div>

									<div class="p-s">
										<%= link_to show_product_url(product) do %>
											<p class="price">$<%= product.price  %></p>
										<% end %>
										<div class="social">
											<%= render 'social', url: show_product_url(product), product: product %>
										</div>
									</div>
								</div>
								<div class="d-tire">
										<%= link_to show_product_url(product) do %>
											<%= image_tag 'ref.jpg' %>
										<% end %>
								</div>
						</div>
					</div>
				</div>
			<% end %>
		</div>
	</div>
	<%= will_paginate @products, page_links: true, class: "text-center will-paginate" %>
	
</div>

app/views/front/brand_search.html.erb
<%= render 'shared/navigation' %>

<div class="container-2">
	<div class="row">
		
		<div class="col s12">
			<% if params[:brand] %>
				<div class="col s12 head">
					<h5 class="b"><%= "##{params[:brand]}" %></h5>	
				</div>	
			<% end %>
			<% @products.each do |product| %>
				<div class="col s12 m12 l6">
					<div class="d-1 <%= cycle('odd', 'even') %>">

						<div class="cont-tire hoverable">
								<div class="d-2">
									<% if product.brand %>
										<div class="brand">
											<%= link_to brand_search_path(product.brand.name) do %>
												<h4 class="y">
													<%= product.brand.name.upcase %>
												</h4>
											<% end %>
										</div>
									<% end %>
									<div class="title">
										<%= link_to show_product_url(product) do %>
											<h2>
												<%= product.title.upcase %>
											</h2>
										<% end %>
									</div>
									<div class="sizes">
										<% if product.category.name == 'llanta' %>
											<%= link_to show_product_url(product) do %>
												<h4>
													<%= product.ancho %>-<%= product.perfil %>-<%= product.rin %>
												</h4>
											<% end %>
										<% end %>
									</div>

									<div class="p-s">
										<%= link_to show_product_url(product) do %>
											<p class="price">$<%= product.price  %></p>
										<% end %>
										<div class="social">
											<%= render 'social', url: show_product_url(product), product: product %>
										</div>
									</div>
								</div>
								<div class="d-tire">
										<%= link_to show_product_url(product) do %>
											<% if product.category.name == 'llanta' %>
												<%= image_tag 'tire-d.jpg' %>
											<% elsif product.category.name == 'refaccion' %>
												<%= image_tag 'ref.jpg' %>
											<% else %>
												<%= image_tag 'rancho.jpg' %>
											<% end %>
										<% end %>
								</div>
						</div>
					</div>
				</div>
			<% end %>
		</div>
	</div>
	<%= will_paginate @products, page_links: true, class: "text-center will-paginate" %>
</div>

app/views/front/index.html.erb
<%= render 'shared/navigation' %>


<% if @st %>
	<%= search_form_for(@st, html: {class: "form1"}) do |f| %>
	<% end %>
<% end %>


<% if @promos %>
	<div class="promos hide-on-small-only">
			<% @promos.each do |promo| %>
				<div class="promo">
					<% if promo.url? %>
						<a href="<%= promo.url %>">
							<%= image_tag promo.img.url() %>
						</a>
					<% else %>
						<%= image_tag promo.img.url() %>
					<% end %>
				</div>
			<% end %>
	</div>
<% end %>

<div class="container-2" id="search">
	<div class="search-container">
			<div class="row">
				<div class="col s12 l6 center">
					<div class="form-1">
						<h5 class="grey-text ">Buscar por</h5>
						<h3 class="">Vehículo</h3>
						<%= search_form_for(@st, url: search_result_path) do |f| %>

							<%= f.select(:cars_year_eq, 1960..(Date.today.year+1), {prompt: 'año'}, class: "grey-text") %>
							<%= f.collection_select :cars_car_brand_id_eq, CarBrand.all, :id, :name, {prompt: 'marca'}, class: "grey-text" %>
							<%= f.collection_select :cars_model_eq, Car.models, :model, :model, {prompt: 'modelo'}, class: "grey-text " %>
			        <%= f.button "Buscar", class: "btn amber" %>

						<% end %>
					</div>
				</div>
				<div class="col s12 l6 center">
					<div class="form-1">

						<h5 class="grey-text ">Buscar por</h5>
						<h3 class="">Tamaño llanta</h3>
						<%= search_form_for(@st, url: search_result_path) do |f| %>
								<%= f.collection_select :ancho_eq, Product.select(:ancho).distinct, :ancho, :ancho, {prompt: 'ancho'}, class: "grey-text" %>

							<%= f.collection_select :perfil_eq, Product.select(:perfil).distinct, :perfil, :perfil, {prompt: 'perfil'}, class: "grey-text" %>
							<%= f.collection_select :rin_eq, Product.select(:rin).distinct, :rin, :rin, {prompt: 'rin'},  class: "grey-text" %>
							<%= f.button 'Buscar', class: 'btn amber' %>
						<% end %>
					</div>

				</div>

				<div class="col s12 center">
					<div class="form-2">
						<h5 class="grey-text">Buscar por</h5><h3>Palabras</h3>
						<div class="row">
							<%= search_form_for(@st, url: search_result_path) do |f| %>
								<%= f.text_field :title_cont, class: "col s12 l7 grey-text" %>
								<%= f.collection_select :brand_id_eq, Brand.all, :id, :name, {prompt: 'marca'}, class: "col s12 l3 grey-text" %>
								<div class="col s12 l2">
									<%= f.button 'Buscar', class: 'btn amber' %>
								</div>
							<% end %>

						</div>
					</div>
				</div>
			</div>
	</div>
</div>

<div class="container-2">
	<div class="row">
		<div class="col s12">
			<ul class="tabs">
				<li class="tab col s2 m3"><a href="#new" class="active">lo más nuevo</a></li>
				<li class="tab col s2 m3"><a href="#best_offers" class="">ofertas</a></li>
				<li class="tab col s2 m3"><a href="#parts">refacciones</a></li>
				<li class="tab col s2 m3"><a href="#suspensions">suspensiones</a></li>
			</ul>
		</div>

		<!-- contenido -->
		<div id="new" class="col s12 tabss">
			<% @products.each do |product| %>
				<div class="col s12 m12 l6">
					<div class="d-1 <%= cycle('odd', 'even') %>">

						<div class="cont-tire hoverable">
								<div class="d-2">
									<% if product.brand %>
										<div class="brand">
											<%= link_to brand_search_path(product.brand.name) do %>
												<h4 class="y">
													<%= product.brand.name.upcase %>
												</h4>
											<% end %>
										</div>
									<% end %>
									<div class="title">
										<%= link_to show_product_url(product) do %>
											<h2>
												<%= product.title.upcase %>
											</h2>
										<% end %>
									</div>
									<div class="sizes">
										<%= link_to show_product_url(product) do %>
											<h4>
												<%= product.ancho %>-<%= product.perfil %>-<%= product.rin %>
											</h4>
										<% end %>
									</div>

									<div class="p-s">
										<%= link_to show_product_url(product) do %>
											<p class="price">$<%= product.price  %></p>
										<% end %>
										<div class="social">
											<%= render 'social', url: show_product_url(product), product: product %>
										</div>
									</div>
								</div>
								<div class="d-tire">
									<% if product.galleries.blank? %>
										<%= link_to show_product_url(product) do %>
											<%= image_tag 'd-tire.jpg' %>
										<% end %>
									<% else %>
										<%= link_to show_product_url(product) do %>
											<%= image_tag product.galleries.first.photo.url %>
										<% end %>
									<% end %>
								</div>
						</div>
					</div>
				</div>
			<% end %>

			<div class="button s12">
				<%= link_to 'ver catalogo completo', tires_path, class: "btn" %>
			</div>

		</div>


		<div id="best_offers" class="col s12 tabss">
			<% @featured.each do |product| %>
				<div class="col s12 m12 l6">
					<div class="d-1 <%= cycle('odd', 'even') %>">

						<div class="cont-tire hoverable">
								<div class="d-2">
									<% if product.brand %>
										<div class="brand">
											<%= link_to brand_search_path(product.brand.name) do %>
												<h4 class="y">
													<%= product.brand.name.upcase %>
												</h4>
											<% end %>
										</div>
									<% end %>
									<div class="title">
										<%= link_to show_product_url(product) do %>
											<h2>
												<%= product.title.upcase %>
											</h2>
										<% end %>
									</div>
									<div class="sizes">
										<%= link_to show_product_url(product) do %>
											<h4>
												<% if product.category.name == "llanta" %>
													<%= product.ancho %>-<%= product.perfil %>-<%= product.rin %>
												<% end %>
											</h4>
										<% end %>
									</div>

									<div class="p-s">
										<%= link_to show_product_url(product) do %>
											<p class="price">$<%= product.price  %></p>
										<% end %>
										<div class="social">
											<%= render 'social', url: show_product_url(product), product: product %>
										</div>
									</div>
								</div>
								<div class="d-tire">
										<%= link_to show_product_url(product) do %>
											<% if product.category.name == 'llanta' %>
												<%= image_tag 'd-tire.jpg' %>
											<% elsif product.category.name == "refaccion" %>
												<%= image_tag 'ref.jpg' %>
											<% else %>
												<%= image_tag 'rancho.jpg' %>
											<% end %>
										<% end %>
								</div>
						</div>
					</div>
				</div>
			<% end %>
			<div class="button s12">
				<%= link_to 'ver todas las ofertas', offers_path, class: "btn" %>
			</div>
		</div>

		<!-- auto parts -->
		<div id="parts" class="col s12 tabss">
			<% @auto_parts.each do |product| %>
				<div class="col s12 m12 l6">
					<div class="d-1 <%= cycle('odd', 'even') %>">

						<div class="cont-tire hoverable">
								<div class="d-2">
									<% if product.brand %>
										<div class="brand">
											<%= link_to brand_search_path(product.brand.name) do %>
												<h4 class="y">
													<%= product.brand.name.upcase %>
												</h4>
											<% end %>
										</div>
									<% end %>
									<div class="title">
										<%= link_to show_product_url(product) do %>
											<h2>
												<%= product.title.upcase %>
											</h2>
										<% end %>
									</div>
									

									<div class="p-s">
										<%= link_to show_product_url(product) do %>
											<p class="price">$<%= product.price  %></p>
										<% end %>
										<div class="social">
											<%= render 'social', url: show_product_url(product), product: product %>
										</div>
									</div>
								</div>
								<div class="d-tire">
										<%= link_to show_product_url(product) do %>
											<%= image_tag 'ref.jpg' %>
										<% end %>
								</div>
						</div>
					</div>
				</div>
			<% end %>
			<div class="button s12">
				<%= link_to 'ver catalogo completo', auto_parts_path, class: "btn" %>
			</div>
		</div>
		<div id="suspensions" class="col s12 tabss">
			<% @suspensions.each do |product| %>
				<div class="col s12 m12 l6">
					<div class="d-1 <%= cycle('odd', 'even') %>">

						<div class="cont-tire hoverable">
								<div class="d-2">
									<% if product.brand %>
										<div class="brand">
											<%= link_to brand_search_path(product.brand.name) do %>
												<h4 class="y">
													<%= product.brand.name.upcase %>
												</h4>
											<% end %>
										</div>
									<% end %>
									<div class="title">
										<%= link_to show_product_url(product) do %>
											<h2>
												<%= product.title.upcase %>
											</h2>
										<% end %>
									</div>
									

									<div class="p-s">
										<%= link_to show_product_url(product) do %>
											<p class="price">$<%= product.price  %></p>
										<% end %>
										<div class="social">
											<%= render 'social', url: show_product_url(product), product: product %>
										</div>
									</div>
								</div>
								<div class="d-tire">
										<%= link_to show_product_url(product) do %>
											<%= image_tag 'rancho.jpg' %>
										<% end %>
								</div>
						</div>
					</div>
				</div>
			<% end %>
			<div class="button s12">
				<%= link_to 'ver catalogo completo', suspensions_path, class: "btn" %>
			</div>
		</div>
	</div>
</div>


<script type="text/javascript">
	$(document).ready(function(){
		$('.promos').slick({
			infinite: true,
		  slidesToShow: 1,
		  slidesToScroll: 1,
		  autoplay: true,
		  dots: false,
		  prevArrow: "<button type='button' class='slick-prev'><i class='material-icons'>skip_previous</i></button>",
		  nextArrow: "<button type='button' class='slick-next'><i class='material-icons'>skip_next</i></button>"
		});
	});
</script>

app/views/front/offers.html.erb
<%= render 'shared/navigation' %>

<div class="container-2">
	<div class="row">
		
		<div class="col s12">
			<div class="col s12 head">
				<h5 class="y">Las mejores ofertas</h5>	
			</div>	
			<% @offers.each do |product| %>
				<div class="col s12 m12 l6">
					<div class="d-1 <%= cycle('odd', 'even') %>">

						<div class="cont-tire hoverable">
								<div class="d-2">
									<% if product.brand %>
										<div class="brand">
											<%= link_to brand_search_path(product.brand.name) do %>
												<h4 class="y">
													<%= product.brand.name.upcase %>
												</h4>
											<% end %>
										</div>
									<% end %>
									<div class="title">
										<%= link_to show_product_url(product) do %>
											<h2>
												<%= product.title.upcase %>
											</h2>
										<% end %>
									</div>
									<div class="sizes">
										<%= link_to show_product_url(product) do %>
											<h4>
												<%= product.ancho %>-<%= product.perfil %>-<%= product.rin %>
											</h4>
										<% end %>
									</div>

									<div class="p-s">
										<%= link_to show_product_url(product) do %>
											<p class="price">$<%= product.price  %></p>
										<% end %>
										<div class="social">
											<%= render 'social', url: show_product_url(product), product: product %>
										</div>
									</div>
								</div>
								<div class="d-tire">
										<%= link_to show_product_url(product) do %>
											<%= image_tag 'tire-d.jpg' %>
										<% end %>
								</div>
						</div>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/front/search_result.html.erb
<%= render 'shared/navigation' %>


<div class="container-2">
	<div class="row">
		
		<div class="col s12">
			<% if params[:tag] %>
				<div class="col s12 head">
					<h5 class="b"><%= "##{params[:tag]}" %></h5>	
				</div>	
			<% end %>
			<% @products.each do |product| %>
				<div class="col s12 m12 l6">
					<div class="d-1 <%= cycle('odd', 'even') %>">

						<div class="cont-tire hoverable">
								<div class="d-2">
									<% if product.brand %>
										<div class="brand">
											<%= link_to brand_search_path(product.brand.name) do %>
												<h4 class="y">
													<%= product.brand.name.upcase %>
												</h4>
											<% end %>
										</div>
									<% end %>
									<div class="title">
										<%= link_to show_product_url(product) do %>
											<h2>
												<%= product.title.upcase %>
											</h2>
										<% end %>
									</div>
									<div class="sizes">
										<% if product.category.name == 'llanta' %>
											<%= link_to show_product_url(product) do %>
												<h4>
													<%= product.ancho %>-<%= product.perfil %>-<%= product.rin %>
												</h4>
											<% end %>
										<% end %>
									</div>

									<div class="p-s">
										<%= link_to show_product_url(product) do %>
											<p class="price">$<%= product.price  %></p>
										<% end %>
										<div class="social">
											<%= render 'social', url: show_product_url(product), product: product %>
										</div>
									</div>
								</div>
								<div class="d-tire">
										<%= link_to show_product_url(product) do %>
											<% if product.category.name == 'llanta' %>
												<% if product.galleries.blank? %>
													<%= image_tag 'd-tire.jpg' %>
												<% else %>
													<%= image_tag product.galleries.first.photo.url %>
												<% end %>
											<% elsif product.category.name == 'refaccion' %>
												<%= image_tag 'ref.jpg' %>
											<% else %>
												<%= image_tag 'rancho.jpg' %>
											<% end %>
										<% end %>
								</div>
						</div>
					</div>
				</div>
			<% end %>
		</div>
	</div>
	<%= will_paginate @products, page_links: true, class: "text-center will-paginate" %>
</div>

app/views/front/show_product.html.erb
<%= render 'shared/navigation' %>


<div class="white">
	<div class="container">
		<div class="row">
			<div class="col s12 l6 ">

				<div class="col s12">
					<div class="slider-for">
						<% unless @product.galleries.empty? %>
						  <% @product.galleries.each do |g| %>
						  	<div>
							    <%= image_tag g.photo.url(:large), size: "300" %>
						  	</div>
						  <% end %>
						<% else %>
							<div>
							  <%= image_tag 'notire.svg', size: "300" %>
							</div>
						<% end %>
					</div>

				</div>
				<div class="col s12">
					<div class="small-picture">
						<% unless @product.galleries.empty? %>
						  <% @product.galleries.each do |g| %>
						   <div>
						    <%= image_tag g.photo.url(:small), size: "50" %>
						   </div>
						  <% end %>
						<% else %>
							<div>
							  <%= image_tag 'notire.svg', size: "50" %>
							</div>
						<% end %>
					</div>
				</div>


			</div>


			<div class="col s12 l6">

				<% if user_signed_in? %>
				  <% if current_user.is?(:super) or current_user.is?(:admin) %>
				    <%= link_to 'edit', edit_product_path(@product) %>
				    
				  <% end %>
				<% end %>

				<div class="info">
					<a href="<%= brand_search_path(@product.brand.name) %>"><h4 class="y"><%= @product.brand.name.upcase %></h4></a>
					<h2 class="title"><%= @product.title %></h2>
					<% if @product.category.name == "llanta" %>
						<h5 class="sizes"><%= @product.ancho %>-<%= @product.perfil %>-<%= @product.rin %></h5>
					<% end %>
				</div>
				<div class="content">
					<p><%= sanitize @product.content %></p>
				</div>
				<div class="tags">
				  <% if @product.tags %>
				    <p>
				      <% @product.tags.each do |tag| %>
				      	<%= link_to tag_search_path(tag.name) do %>
					        <%= "##{tag.name} " %>
				      	<% end %>
				      <% end %>
				    </p>
				  <% end %>

				</div>

				<div class="">
					<p class="price">$<%= @product.price %></p>
				</div>


			    <%= form_for(@line_item, url: line_items_path(product_id: @product.id), class: "col s12") do |f| %>
			      <div class="col s2">
			        <%= f.label :quantity, 'cantidad' %>
			        <%= f.number_field :quantity, min: 1, max: 99 %>
			      </div>
			      <div class="col s10">
			        <%= f.button "añadir al carrito", remote: false, class: "btn" %>
			      </div>


			    <% end %>


			</div>





		</div>
	</div>
</div>

<div class="grey lighten-2">
	<div class="container">
		<div class="row">
			<div class="col s12 performances">
				<div class="col s6 l3 performance">
					<h5>Rendimiento en frio</h5><br>
					<progress value="<%= @product.performance_cold %>" max="10" class=""></progress>
				</div>

				<div class="col s6 l3 performance">
					<h5>Rendimiento en seco</h5><br>
					<progress value="<%= @product.performance_dry %>" max="10" class=""></progress>

				</div>
				<div class="col s6 l3 performance">
					<h5>Rendimiento en mojado</h5><br>
					<progress value="<%= @product.performance_wet %>" max="10" class=""></progress>
				</div>

				<div class="col s6 l3 performance">
					<h5>Kilometros de rendimiento</h5><br>
					<p><%= @product.performance_km %> Km</p>

				</div>

			</div>
		</div>
	</div>
</div>
<div class="grey grey lighten-2">
	<div class="container">
		<div class="row">

			<div class="col s12 share">
				<h5>Comparte</h5><br>
				<%= render 'social', url: show_product_url(@product), product: @product %>
			</div>
			<div class="col s12 disqus-container">
				<%= render 'disqus', title: @product.title, url: show_product_url(@product) %>
			</div>
		</div>
	</div>
</div>




	<script type="text/javascript">
		$('.slider-for').slick({
		  slidesToShow: 1,
		  slidesToScroll: 1,
		  arrows: false,
		  fade: true,
		  asNavFor: '.small-picture'
		});
		$('.small-picture').slick({
		  slidesToShow: 6,
		  slidesToScroll: 1,
		  asNavFor: '.slider-for',
		  dots: false,
		  centerMode: true,
		  focusOnSelect: true
		});
	</script>

app/views/front/suspensions.html.erb
<%= render 'shared/navigation' %>

<div class="container-2">
	<div class="row">
	
		<div class="col s12">
			<div class="col s12 head">
				<h5 class="b">Suspensiones</h5>	
			</div>	
			<% @products.each do |product| %>
				<div class="col s12 m12 l6">
					<div class="d-1 <%= cycle('odd', 'even') %>">

						<div class="cont-tire hoverable">
								<div class="d-2">
									<% if product.brand %>
										<div class="brand">
											<%= link_to brand_search_path(product.brand.name) do %>
												<h4 class="y">
													<%= product.brand.name.upcase %>
												</h4>
											<% end %>
										</div>
									<% end %>
									<div class="title">
										<%= link_to show_product_url(product) do %>
											<h2>
												<%= product.title.upcase %>
											</h2>
										<% end %>
									</div>
									<div class="sizes">
										
									</div>

									<div class="p-s">
										<%= link_to show_product_url(product) do %>
											<p class="price">$<%= product.price  %></p>
										<% end %>
										<div class="social">
											<%= render 'social', url: show_product_url(product), product: product %>
										</div>
									</div>
								</div>
								<div class="d-tire">
										<%= link_to show_product_url(product) do %>
											<%= image_tag 'rancho.jpg' %>
										<% end %>
								</div>
						</div>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>