config/routes.rb
Rails.application.routes.draw do
  resources :promos
  resources :line_items do 
    collection do
      put 'update-multiple', to: 'line_items#update_multiple', as: :update_multiple
    end
  end

  get 'page/:id', to: 'pages#front_show', as: :front_show

  scope '/admin' do
    resources :categories, :tags, :products, :years, :brands, :carts, :cars, :car_brands, :pages

    resources :charges do 
      put 'send-number', to: 'charges#send_number'
    end

    delete 'galleries/:id', to: 'galleries#destroy', as: :delete_gallerie

  end

  devise_for :users

  root 'front#index'
  get 'products/:id', to: 'front#show_product', as: :show_product
  get 'search', to: 'front#search_result', as: :search_result

  post 'products/:product_id/like', to: 'products/likes#create', as: :increase_like
  delete 'products/:product_id/like', to: 'products/likes#destroy', as: :destroy_like

  get 'cart-resume', to: 'charges#cart_resume', as: :cart_resume
  post 'charge/new', to: 'charges#credit', as: :credit_pay

  get 'charge/new-credit-direct', to: 'charges#credit_1', as: :credit_1
  get 'charge/new-credit-direct-3', to: 'charges#credit_2', as: :credit_2
  get 'charge/new-credit-direct-6', to: 'charges#credit_3', as: :credit_3

  get 'charge/new-oxxo', to: 'charges#oxxo', as: :oxxo
  post 'charge/new-oxxo/pay', to: 'charges#oxxo_pay', as: :oxxo_pay

  get 'charge/show/:id', to: 'charges#show_charge', as: :show_charge

  post 'charge/new-1', to: 'charges#create_1', as: :charge_1
  post 'charge/new-2', to: 'charges#create_2', as: :charge_2
  post 'charge/new-3', to: 'charges#create_3', as: :charge_3

  get "admin", to: 'charges#index'

  get "admin/users/defaults-users" => 'admin#n_users', as: :n_users
  get "admin/users/admins-users" => 'admin#a_users', as: :a_users

  get "admin/user/new" => 'admin#new_user', as: :new_user
  post "admin/user" => 'admin#create_user'

  get "admin/user/:id" => 'admin#show_user', as: :admin_show_user

  get "admin/user/:id/edit" => 'admin#edit', as: :user_edit
  delete "admin/user/:id" => 'admin#destroy_user', as: :user_delete

  patch "admin/user/:id" => 'admin#update'
  put "admin/user/:id" => 'admin#update', as: :user_edit_s

  get 'tags/:tag', to: 'front#search_result', as: :tag_search
  get 'brand/:brand', to: 'front#brand_search', as: :brand_search

  get 'tires', to: 'front#tires', as: :tires
  get 'auto-parts', to: 'front#auto_parts', as: :auto_parts
  get 'suspensions', to: 'front#suspensions', as: :suspensions
  get 'offers', to: 'front#offers', as: :offers

end

app/views/admin/_form.html.erb
<%= form_for(@user, url: user_edit_s_path) do |f| %>

		<div class="whiten-shadow">
			<p><%= @user.name %></p>
			<p><%= @user.email %></p>
		</div>
		
		<% if current_user.is? :super %>
			<%= f.radio_button :role, :admin %>
			<%= f.label :admin %>
			<%= f.radio_button :role, :default %>
			<%= f.label :default %>
		<% end %>

		<br>
		<%= f.button "update", class: "button", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i>"} %>
<% end %>

app/views/admin/_form2.html.erb
<%= form_for(@user, url: admin_user_path) do |f| %>
	 <% if @user.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

	      <ul>
	      <% @user.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>

	<%= f.text_field :name, class: "form-control", placeholder: "nombre" %>
	<%= f.email_field :email, class: "form-control", placeholder: "email" %>
	<%= f.password_field :password, autocomplete: "off", class: "form-control", placeholder: "contraseña" %>
	<%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control", placeholder: "confirmacion de contraseña" %>

	<%= f.radio_button :role, :admin, checked: true  %>
	<%= f.label :admin%>
	<%= f.radio_button :role, :default %>
	<%= f.label :default %><br>


	<%= f.button 'crear usuario', class: "button", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i>"} %>
<% end %>

app/views/admin/_nav.html.erb
<nav class="<%= 'blue' if current_user.is?(:admin) %>">
  <div class="nav-wrapper container-nav">
    <a href="<%= admin_path %>" class="brand-logo">
      Panel de control
    </a>
    <a href="#" data-activates="mobile1" class="button-collapse"><i class="mdi-navigation-menu"></i></a>

    <ul class="right hide-on-med-and-down">

        <li class="<%= 'active' if current_page?(charges_path) %>"><a href="<%= charges_path %>">Ventas</a></li>
        <li class="<%= 'active' if current_page?(products_path) %>"><a href="#!" class="dropdown-button" data-activates="dropdown2">Productos<i class="mdi-navigation-arrow-drop-down right"></i></a></li>
        <li><a href="#!" class="dropdown-button" data-activates="dropdown1">Usuarios<i class="mdi-navigation-arrow-drop-down right"></i></a></li>
        <li><a href="#!" class="dropdown-button" data-activates="dropdown4">Otros<i class="mdi-navigation-arrow-drop-down right"></i></a></li>

      
        <li class="<%= 'active' if current_page?(edit_user_registration_path) %> tooltipped" data-position="bottom" data-tooltip="Mi perfil">
          <%= link_to edit_user_registration_path do %>
            <i class="mdi-action-account-circle"></i>
          <% end %>
        </li>
        <li class="tooltipped" data-position="bottom" data-tooltip="Ir a tienda">
          <%= link_to root_path, class: "" do %>
            <i class="mdi-maps-store-mall-directory"></i>
          <% end %>
        </li>
        <li>
          <%= link_to :salir, destroy_user_session_path, method: :delete %>
        </li>
    </ul>

    <ul class="side-nav" id="mobile1">
      <li><a href="#!" class="dropdown-button">Usuarios<i class="mdi-navigation-arrow-drop-down right"></i></a></li>
    </ul>

  </div>

  <!-- Dropdowns -->
  <ul id="dropdown1" class="dropdown-content">
    <li class="<%= 'active' if current_page?(a_users_path) %>"><%= link_to "Admins", a_users_path %></li>
    <li class="<%= 'active' if current_page?(n_users_path) %>"><%= link_to "Usuarios", n_users_path %></li>
   
  </ul>

  <ul id="dropdown2" class="dropdown-content">
    <li class="<%= 'active' if current_page?(products_path) %>"><%= link_to "Productos", products_path %></li>
    <li class="divider"></li>
    <li class="<%= 'active' if current_page?(categories_path) %>"><%= link_to "Categorias", categories_path %></li>
    <li class="<%= 'active' if current_page?(brands_path) %>"><%= link_to "Marcas de llantas", brands_path %></li>
    <li class="<%= 'active' if current_page?(tags_path) %>"><%= link_to "Tags", tags_path %></li>
    <li class="divider"></li>
    <li class="<%= 'active' if current_page?(cars_path) %>"><%= link_to "Vehiculos", cars_path %></li>
    <li class="<%= 'active' if current_page?(car_brands_path) %>"><%= link_to "Marca vehículo", car_brands_path %></li>

  </ul>

  
  <ul id="dropdown4" class="dropdown-content">
    <li class="<%= 'active' if current_page?(promos_path) %>"><%= link_to "Slides", promos_path %></li>
    <li class="<%= 'active' if current_page?(pages_path) %>"><%= link_to "Páginas", pages_path %></li>
  </ul>
</nav>

app/views/admin/a_users.html.erb
<%= render 'nav' %>

<div class="container">
	<br>
	<h3>Usuarios admins</h3>


	<%= search_form_for(@st, url: a_users_path, html:{class: "whiten-shadow"}) do |f| %>
		<div class="row">
			<div class="col s12">
				<div class="s12">
			    <%= f.search_field :name_or_email_cont, {placeholder: "nombre o email...", class: "form-control"} %>
				</div>
			</div>
			<div class="col s9">
     
        <%= f.button 'buscar', class: "btn expand" %>
      </div>
      <div class="col s3">
        <%= link_to 'reestablecer', a_users_path, class: "btn amber" %>
      </div>
			<div class="col s12">
			<% if current_user.is? :super %>
		    <%= link_to new_user_path do %>
		    		<i class="fa fa-plus plus-icon" data-toggle="tooltip" data-placement="left" title="nuevo usuario"></i>
		    <% end %>
    	<% end %>
			</div>
		</div>
  <% end %>
	
	
		<table class="striped centered">
			<thead>
				<tr>
					<th>#</th>
					<th>name</th>
					<th>email</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
					<tr>
						<td><%= user.id %></td>
						<td><%= user.name %></td>
						<td><%= user.email %></td>
						<td class="">
							<%= link_to admin_show_user_path(user) do %>
										<i class="fa fa-eye" data-toggle="tooltip" data-placement="top" title="ver"></i>
									<% end %>
									<% if current_user.is? :super %>
										<%= link_to user_edit_path(user) do %>
											<i class="fa fa-edit" data-toggle="tooltip" data-placement="top" title="editar"></i>
										<% end %>
										<%= link_to user_delete_path(user), method: :delete, data: { confirm: "¿Estas seguro?"} do %>
											<i class="fa fa-close" data-toggle="tooltip" data-placement="top" title="eliminar"></i>
										<% end %>
									<% end %>
						</td>
					</tr>
				<% end %>	
			</tbody>
		</table>
		
	<%= will_paginate @users, page_links: false, class: "text-center will-paginate" %>
</div>

app/views/admin/charts.html.erb
<%= render 'nav' %>

<div class="container-fluid">
	<p>pendiente</p>
</div>

app/views/admin/edit.html.erb
<%= render 'nav' %>

<div class="container-fluid">
	<h2>edit</h2>
	<%= render 'form' %>
</div>

app/views/admin/n_users.html.erb
<%= render 'nav' %>

	
<div class="container">
<br>
	<h3>Usuarios normales</h3>

	<%= search_form_for(@st, url: n_users_path, html:{class: "whiten-shadow"}) do |f| %>
		<div class="row">
			<div class="col s12">
				<div class="s12">
			    <%= f.search_field :name_or_email_cont, {placeholder: "nombre o email...", class: "form-control"} %>
				</div>
			</div>
			<div class="col s9">
     
        <%= f.button 'buscar', class: "btn expand" %>
      </div>
      <div class="col s3">
        <%= link_to 'reestablecer', n_users_path, class: "btn amber" %>
      </div>
			<div class="col s12">
			<% if current_user.is? :super %>
		    <%= link_to new_user_path do %>
		    		<i class="fa fa-plus plus-icon" data-toggle="tooltip" data-placement="left" title="nuevo usuario"></i>
		    <% end %>
    	<% end %>
			</div>
		</div>
  <% end %>
	
		<table class="striped centered">
			<thead>
				<tr>
					<th>#</th>
					<th>name</th>
					<th>email</th>
					<th></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
					<tr>
						<td><%= user.id %></td>
						<td><%= user.name %></td>
						<td><%= user.email %></td>
						<td class="">
							<%= link_to admin_show_user_path(user) do %>
										<i class="fa fa-eye" data-toggle="tooltip" data-placement="top" title="ver"></i>
									<% end %>
									<% if current_user.is? :super %>
										<%= link_to user_edit_path(user) do %>
											<i class="fa fa-edit" data-toggle="tooltip" data-placement="top" title="editar"></i>
										<% end %>
										<%= link_to user_delete_path(user), method: :delete, data: { confirm: "¿Estas seguro?"} do %>
											<i class="fa fa-close" data-toggle="tooltip" data-placement="top" title="eliminar"></i>
										<% end %>
									<% end %>
						</td>
					</tr>
				<% end %>	
			</tbody>
		</table>


		
	<%= will_paginate @users, page_links: true, class: "text-center will-paginate" %>
</div>

app/views/admin/new_user.html.erb
<%= render 'nav' %>

<div class="container-fluid">
	<h2>new user</h2>
	<%= render 'form2' %>
</div>

app/views/admin/show_user.html.erb
<%= render 'nav' %>

<div class="container-fluid">
	<div class="hu">
		<%= link_to 'atras', :back, class: "button" %>
	

	</div><br>

		<div class="whiten-shadow">
			<p><%= @user.name %></p>
			<p><%= @user.email %></p>
			<p>rol: <%= @user.role %></p>
			<% if @user.confirmed_at %>
				<p>confirmacion email: <%= @user.confirmed_at %></p>
			<% else %>
				<p>correo no confirmado</p>
			<% end %>
			<p>contador sesiones: <%= @user.sign_in_count %></p>
			<p>ultima vez conectado: <%= local_time(@user.current_sign_in_at, '%b %e, %Y') if @user.current_sign_in_at %></p>
			<p>Fecha de creacion: <%= local_time @user.created_at, '%b %e, %Y' %></p>


		</div>

		<h4 class="table-header">compras</h4>
		<table class="table table-hover">
		<thead>
			<tr>
				<th>#</th>
				<th>nombre</th>
				<th>email</th>
				<th>Rol</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			
		</tbody>
	</table>


</div>