config/routes.rb
Rails.application.routes.draw do
  resources :promos
  resources :line_items do 
    collection do
      put 'update-multiple', to: 'line_items#update_multiple', as: :update_multiple
    end
  end

  get 'page/:id', to: 'pages#front_show', as: :front_show

  scope '/admin' do
    resources :categories, :tags, :products, :years, :brands, :carts, :cars, :car_brands, :pages

    resources :charges do 
      put 'send-number', to: 'charges#send_number'
    end

    delete 'galleries/:id', to: 'galleries#destroy', as: :delete_gallerie

  end

  devise_for :users

  root 'front#index'
  get 'products/:id', to: 'front#show_product', as: :show_product
  get 'search', to: 'front#search_result', as: :search_result

  post 'products/:product_id/like', to: 'products/likes#create', as: :increase_like
  delete 'products/:product_id/like', to: 'products/likes#destroy', as: :destroy_like

  get 'cart-resume', to: 'charges#cart_resume', as: :cart_resume
  post 'charge/new', to: 'charges#credit', as: :credit_pay

  get 'charge/new-credit-direct', to: 'charges#credit_1', as: :credit_1
  get 'charge/new-credit-direct-3', to: 'charges#credit_2', as: :credit_2
  get 'charge/new-credit-direct-6', to: 'charges#credit_3', as: :credit_3

  get 'charge/new-oxxo', to: 'charges#oxxo', as: :oxxo
  post 'charge/new-oxxo/pay', to: 'charges#oxxo_pay', as: :oxxo_pay

  get 'charge/show/:id', to: 'charges#show_charge', as: :show_charge

  post 'charge/new-1', to: 'charges#create_1', as: :charge_1
  post 'charge/new-2', to: 'charges#create_2', as: :charge_2
  post 'charge/new-3', to: 'charges#create_3', as: :charge_3

  get "admin", to: 'charges#index'

  get "admin/users/defaults-users" => 'admin#n_users', as: :n_users
  get "admin/users/admins-users" => 'admin#a_users', as: :a_users

  get "admin/user/new" => 'admin#new_user', as: :new_user
  post "admin/user" => 'admin#create_user'

  get "admin/user/:id" => 'admin#show_user', as: :admin_show_user

  get "admin/user/:id/edit" => 'admin#edit', as: :user_edit
  delete "admin/user/:id" => 'admin#destroy_user', as: :user_delete

  patch "admin/user/:id" => 'admin#update'
  put "admin/user/:id" => 'admin#update', as: :user_edit_s

  get 'tags/:tag', to: 'front#search_result', as: :tag_search
  get 'brand/:brand', to: 'front#brand_search', as: :brand_search

  get 'tires', to: 'front#tires', as: :tires
  get 'auto-parts', to: 'front#auto_parts', as: :auto_parts
  get 'suspensions', to: 'front#suspensions', as: :suspensions
  get 'offers', to: 'front#offers', as: :offers

end

app/views/shared/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= GOOGLE_ANALYTICS_ID %>', 'auto');
  ga('send', 'pageview');

</script>

app/views/shared/_cart_box.html.erb
<% if @cart %>
	<div class="cart-box">
		<div class="image-cart"></div>
		<div class="counter">
			<%= @cart.line_items.count %>
		</div>
		<div class="inner">
			<div class="inner-content2" id="cart-line">			
				<%= render 'line_items/line_item' %>
			</div>
		</div>
	</div>
<% end %>

app/views/shared/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = '<%= DISQUS_SHORTNAME %>' ; // required: replace example with your forum shortname
    // var disqus_identifier = 'a unique identifier for each page where Disqus is present';
    var disqus_title = '<%= title %>';
    var disqus_url = '<%= url %>';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/shared/_footer.html.erb
<section class="footer" id="footer">
	<div class="f-container">
		<div class="row">


			<div class="col l4 s12 links">
				<h5 class="white-text">Enlaces</h5>
				
				<% @pages.each do |page| %>
					<%= link_to "#{page.title}", front_show_path(page), class: "btn waves-effect grey darken-1" %>
				<% end %>
			</div>

			<div class="col l4 s12 social">
				<h5 class="white-text">Conecta con nosotros</h5><br>
				<a href="<%= FACEBOOK_URL %>" class="icon" ><%= image_tag 'face2.svg' %></a>
				<a href="<%= INSTAGRAM_URL %>" class="icon" ><%= image_tag 'instagram2.svg' %></a>
				<p class="white-text"><%= image_tag 'skype.svg', class: "phone" %>sotollantas</p>
				<p class="white-text"><%= image_tag 'phone2.svg', class: "phone" %>348 122 17 05</p>
				<p class="white-text"><%= image_tag 'phone2.svg', class: "phone" %>348 102 31 44</p>
				<p class="white-text"><%= image_tag 'phone2.svg', class: "phone" %>331 614 8037</p>
				<p class="white-text"><%= image_tag 'phone2.svg', class: "phone" %>62*897316*1</p>
				<p class="white-text"><%= EMAIL %></p>
			</div>
			<div class="col l4 s12 visa">
				<%= image_tag 'tr.png' %>
				<%= image_tag 'oxxo.png' %>
				<%= image_tag 'visa.png' %>
				<%= image_tag 'master.png' %>
				<%= image_tag 'paypal.png' %>
				<%= image_tag 'fedex.png' %>
			</div>
		</div>
	</div>
		<div class="copyright">
			<p class="white-text">
				© 2015 Sotollantas, Todos los derechos reservados.
			</p>
		</div>
</section>

app/views/shared/_like.html.erb
	<% if user_signed_in? && current_user.likes?(product) %>
		<%= link_to destroy_like_path(product), method: :delete, remote: true, class: "" do %>
		<%= image_tag 'heart2.svg' %>
		<% end %>
	<% else %>
		<%= link_to increase_like_path(product), method: :post, remote: true, class: "" do %>
			<img class="tooltipped" src="<%= asset_path 'heart.svg' %>" data-position="bottom" data-tooltip="agregar a favoritos">
		<% end %>
	<% end %>
	

app/views/shared/_navigation.html.erb
<div class="navbar-fixed">
	<nav class="navbar">
		<div class="nav-wrapper container-nav">

			<ul class="left hide-on-med-and-down ul-list">
	    		<% if user_signed_in? %>
	    			<% if current_user.is?(:super) or current_user.is?(:admin) %>
	    				<li class="tooltipped" data-position="bottom" data-tooltip="admin" ><a href="<%= admin_path %>"><%= image_tag 'tool.svg', class: "custom-icon" %></a></li>
	    			<% end %>


		    		<li class="tooltipped" data-position="bottom" data-tooltip="ver carrito">
		    			<% unless @cart.line_items.count == 0 %>
								<div class="counter">
									<span><%= @cart.line_items.count %></span>
								</div>
		    			<% end %>
		    			<a href="<%= cart_resume_path %>"><%= image_tag 'cart.svg', class: 'custom-icon' %></a>
		    		</li>

		    		<li>
		    			<a href="#!" class="dropdown-button" data-activates="dropdown_user"><%= image_tag 'users.svg', class: "custom-icon" %></a>
		    		</li>
		    		<li class="tooltipped" data-position="bottom" data-tooltip="buscador" ><a href="<%= root_url %>#search"><%= image_tag 'search.svg', class: 'custom-icon' %></a></li>
	    		<% else %>
		    		<li><a href="<%= cart_resume_path %>"><%= image_tag 'cart.svg', class: 'custom-icon' %></a></li>
		    		<li class="tooltipped" data-position="bottom" data-tooltip="buscador" ><a href="<%= root_url %>#search"><%= image_tag 'search.svg', class: 'custom-icon' %></a></li>

	    			<li class="grey small btn-flat" id="login-btn"><%= link_to 'inicio/registro', new_user_session_path %></li>
	    		<% end %>

	    </ul>

			<a href="<%= root_path %>" class="brand-logo center">
	      <%= image_tag 'soto.png' %> 
	    </a>

	    <ul class="right hide-on-med-and-down">
	    		<li ><a href="<%= FACEBOOK_URL %>"><%= image_tag 'face.svg', class: 'custom-icon' %></a></li>
	    		<li ><a href="#footer"><%= image_tag 'phone.svg', class: 'custom-icon' %></a></li>
	    		<li ><a href="<%= INSTAGRAM_URL %>"><%= image_tag 'instagram.svg', class: 'custom-icon' %></a></li>
	    </ul>


	    <!-- Dropdowns -->
		  <ul id="dropdown_user" class="dropdown-content">
		    <li class="<%= 'active' if current_page?(edit_user_registration_path) %>"><%= link_to "mi perfil", edit_user_registration_path %></li>
		    <li><%= link_to "salir", destroy_user_session_path, method: :delete %></li>
		  </ul>

		  <ul id="slide-out" class="side-nav">
			  <% if user_signed_in? %>
	    			<% if current_user.is?(:super) or current_user.is?(:admin) %>
	    				<li>
	    					<a href="<%= admin_path %>">
	    					<%= image_tag 'tool.svg' %>
	    					Admin
	    					</a>
	    				</li>
	    			<% end %>


		    		<li>
		    			<% unless @cart.line_items.count == 0 %>
								<div class="counter">
									<span><%= @cart.line_items.count %></span>
								</div>
		    			<% end %>
		    			<a href="<%= cart_resume_path %>">
			    			<%= image_tag 'cart.svg' %>
			    			Ver carrito
		    			</a>
		    		</li>

		    		<li class="no-padding">
				      <ul class="collapsible collapsible-accordion">
				        <li>
				          <a class="collapsible-header">Mi perfil<i class="mdi-navigation-arrow-drop-down"></i></a>
				          <div class="collapsible-body">
				            <ul>
				              <li><%= link_to "mi perfil", edit_user_registration_path %></li>
				              <li><%= link_to "Salir", destroy_user_session_path, method: :delete %></li>
				            </ul>
				          </div>
				        </li>
				      </ul>
				    </li>

		    		<li>
		    			<a href="<%= root_url %>#search">
		    			<%= image_tag 'search.svg' %>
		    			Busqueda
		    			</a>
		    		</li>

		    	
	    		<% else %>
		    		<li><a href="<%= cart_resume_path %>"><%= image_tag 'cart.svg' %>Carrito</a></li>
		    		<li ><a href="<%= root_url %>#search"><%= image_tag 'search.svg' %>Busqueda</a></li>

	    			<li class="registro">
		    			<a href="<%= new_user_session_path %>"><%= image_tag 'users.svg' %>inicio/registro</a>
	    			</li>
	    		<% end %>
		  </ul>
		  <a href="#" data-activates="slide-out" class="button-collapse"><i class="mdi-navigation-menu"></i></a>

		</div>
	</nav>
</div>