config/routes.rb
Rails.application.routes.draw do
  resources :promos
  resources :line_items do 
    collection do
      put 'update-multiple', to: 'line_items#update_multiple', as: :update_multiple
    end
  end

  get 'page/:id', to: 'pages#front_show', as: :front_show

  scope '/admin' do
    resources :categories, :tags, :products, :years, :brands, :carts, :cars, :car_brands, :pages

    resources :charges do 
      put 'send-number', to: 'charges#send_number'
    end

    delete 'galleries/:id', to: 'galleries#destroy', as: :delete_gallerie

  end

  devise_for :users

  root 'front#index'
  get 'products/:id', to: 'front#show_product', as: :show_product
  get 'search', to: 'front#search_result', as: :search_result

  post 'products/:product_id/like', to: 'products/likes#create', as: :increase_like
  delete 'products/:product_id/like', to: 'products/likes#destroy', as: :destroy_like

  get 'cart-resume', to: 'charges#cart_resume', as: :cart_resume
  post 'charge/new', to: 'charges#credit', as: :credit_pay

  get 'charge/new-credit-direct', to: 'charges#credit_1', as: :credit_1
  get 'charge/new-credit-direct-3', to: 'charges#credit_2', as: :credit_2
  get 'charge/new-credit-direct-6', to: 'charges#credit_3', as: :credit_3

  get 'charge/new-oxxo', to: 'charges#oxxo', as: :oxxo
  post 'charge/new-oxxo/pay', to: 'charges#oxxo_pay', as: :oxxo_pay

  get 'charge/show/:id', to: 'charges#show_charge', as: :show_charge

  post 'charge/new-1', to: 'charges#create_1', as: :charge_1
  post 'charge/new-2', to: 'charges#create_2', as: :charge_2
  post 'charge/new-3', to: 'charges#create_3', as: :charge_3

  get "admin", to: 'charges#index'

  get "admin/users/defaults-users" => 'admin#n_users', as: :n_users
  get "admin/users/admins-users" => 'admin#a_users', as: :a_users

  get "admin/user/new" => 'admin#new_user', as: :new_user
  post "admin/user" => 'admin#create_user'

  get "admin/user/:id" => 'admin#show_user', as: :admin_show_user

  get "admin/user/:id/edit" => 'admin#edit', as: :user_edit
  delete "admin/user/:id" => 'admin#destroy_user', as: :user_delete

  patch "admin/user/:id" => 'admin#update'
  put "admin/user/:id" => 'admin#update', as: :user_edit_s

  get 'tags/:tag', to: 'front#search_result', as: :tag_search
  get 'brand/:brand', to: 'front#brand_search', as: :brand_search

  get 'tires', to: 'front#tires', as: :tires
  get 'auto-parts', to: 'front#auto_parts', as: :auto_parts
  get 'suspensions', to: 'front#suspensions', as: :suspensions
  get 'offers', to: 'front#offers', as: :offers

end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :car_brand
  has_many :carings
  has_many :products, through: :carings

  scope :models, -> {select(:model).distinct} 
  scope :default, -> {order('created_at desc')}
  

end

app/models/charge.rb
class Charge < ActiveRecord::Base
  belongs_to :user
	has_many :line_items, dependent: :destroy
	validates :name, :full_address, :phone_number, :country, :state, :city, :zip_code, :colonia, presence: true
  
  scope :default, -> {order('created_at desc')}

	Stages = [['En proceso', :en_proceso], ['Pago recibido y listo para envio', :listo_para_envio], ['Enviado', :enviado]]

  States = [
  	['Aguascalientes'], 
  	['Baja California'], 
  	['Baja California Sur'], 
  	['Campeche'], 
  	['Coahuila'], 
  	['Colima']
  ]


  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
		  item.cart_id = nil
		  line_items << item 
	  end
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_charge, only: [:show, :edit, :update, :destroy, :show_charge]
  layout "admin", only: [:index, :show, :edit]
  before_action :check_admin, only: [:index, :show, :new, :edit]


  # GET /charges
  # GET /charges.json
  def index
    @body_class = 'admin'

    @st = Charge.ransack(params[:q])
    @charges = @st.result(distinct: true).default.paginate(per_page: 30, page: params[:page])
  end

  # GET /charges/1
  # GET /charges/1.json
  def show
    @body_class = 'admin'

  end

  # GET /charges/new
  def new

    @charge = Charge.new
  end

  # GET /charges/1/edit
  def edit
    @body_class = 'admin'

  end

  # POST /charges
  # POST /charges.json

  def create
    
  end


  def create_3
    @body_class = "cart"
    @total_kg = @cart.line_items.sum(:weight).to_i
    @subtotal = @cart.total_price_cart
    @ship_price = calculate_shipping_amount @total_kg
    @total = ((@ship_price + @subtotal)* (0.079)) + (@ship_price + @subtotal)


    order_sku = unique_id(@total)

    
    begin
      charge = Conekta::Charge.create({
        amount: (@total * 100),
        currency: "MXN",
        description: "Compra sotollantas",
        reference_id: "#{order_sku}",
        card: params[:conektaTokenId],
        details: {
          name: params[:charge][:name],
          email: current_user.email,
          phone: params[:charge][:phone_number],
          billing_address: {
            company_name: "n/a",
            street1: params[:charge][:full_address],
            city: params[:charge][:city],
            state: params[:charge][:state],
            zip: params[:charge][:zip_code],
            phone: params[:charge][:phone_number],
            email: current_user.email
          }
        }
        #"tok_a4Ff0dD2xYZZq82d9"
      })
      # @charge = Charge.new(charge_params)
      @charge = Charge.new(
          user_id: current_user.id.to_i,
          name: params[:charge][:name],
          full_address: params[:charge][:full_address],
          colonia: params[:charge][:colonia],
          city: params[:charge][:city],
          country: "México",
          state: params[:charge][:state],
          zip_code: params[:charge][:zip_code],
          phone_number: params[:charge][:phone_number],
          livemode: charge.livemode,
          conekta_status: charge.status,
          amount: @total.to_i,
          conekta_id: order_sku,
          payment_type: "Tarjeta de credito",
          delivery_service: "FedEx",
          currency: "MXN"
        )
      @charge.add_line_items_from_cart(@cart)
      @charge.line_items.each do |line_item|
        line_item.product.decrement!(:stock, line_item.quantity)
      end
      @charge.stock_discounted = true
      # @charge.save

      # respond_to do |f|
      if @charge.save

        AdminMailer.charge_paid(@charge).deliver
        AdminMailer.charge_paid_admin(@charge).deliver
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        # respond_with(@charge, location: show_charges_path(@charge))
        # f.html {redirect_to show_charges_path(@charge), notice: "pago procesado!"}

        redirect_to show_charge_path(@charge)
      else
        # f.html {redirect_to root_path, notice: "algo salio mal!"}
        redirect_to root_path
      end  
      # end
    rescue Conekta::ParameterValidationError => e
      #alguno de los parametros fueron invalidos
      puts e.message
    rescue Conekta::ProcessingError => e 
      # la tarjeta no pudo ser procesada, por ejemplo tarjeta declinada
      puts e.message
      redirect_to credit_pay_path, alert: "Tarjeta no pudo ser procesada, la tarjeta fue declinada, intenta nuevamente o con otra tarjeta."
    rescue Conekta::Error => e
      #un error ocurrió que no sucede en el flujo normal de cobros como por ejemplo un auth_key incorrecto
      redirect_to credit_pay_path, alert: "Tarjeta no pudo ser procesada, intenta nuevamente."  
      puts e.message
    
    end

  end

  def create_2
    @body_class = "cart"
    @total_kg = @cart.line_items.sum(:weight).to_i
    @subtotal = @cart.total_price_cart
    @ship_price = calculate_shipping_amount @total_kg
    @total = ((@ship_price + @subtotal)* (0.049)) + (@ship_price + @subtotal)


    order_sku = unique_id(@total)

    
    begin
      charge = Conekta::Charge.create({
        amount: (@total * 100),
        currency: "MXN",
        description: "Compra sotollantas",
        reference_id: "#{order_sku}",
        card: params[:conektaTokenId],
        details: {
          name: params[:charge][:name],
          email: current_user.email,
          phone: params[:charge][:phone_number],
          billing_address: {
            company_name: "n/a",
            street1: params[:charge][:full_address],
            city: params[:charge][:city],
            state: params[:charge][:state],
            zip: params[:charge][:zip_code],
            phone: params[:charge][:phone_number],
            email: current_user.email
          }
        }
        #"tok_a4Ff0dD2xYZZq82d9"
      })
      # @charge = Charge.new(charge_params)
      @charge = Charge.new(
          user_id: current_user.id.to_i,
          name: params[:charge][:name],
          full_address: params[:charge][:full_address],
          colonia: params[:charge][:colonia],
          city: params[:charge][:city],
          country: "México",
          state: params[:charge][:state],
          zip_code: params[:charge][:zip_code],
          phone_number: params[:charge][:phone_number],
          livemode: charge.livemode,
          conekta_status: charge.status,
          amount: @total,
          conekta_id: order_sku,
          payment_type: "Tarjeta de credito",
          delivery_service: "FedEx",
          currency: "MXN"
        )
      @charge.add_line_items_from_cart(@cart)
      @charge.line_items.each do |line_item|
        line_item.product.decrement!(:stock, line_item.quantity)
      end
      @charge.stock_discounted = true
      # @charge.save

      # respond_to do |f|
      if @charge.save

        AdminMailer.charge_paid(@charge).deliver
        AdminMailer.charge_paid_admin(@charge).deliver
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        # respond_with(@charge, location: show_charges_path(@charge))
        # f.html {redirect_to show_charges_path(@charge), notice: "pago procesado!"}

        redirect_to show_charge_path(@charge)
      else
        # f.html {redirect_to root_path, notice: "algo salio mal!"}
        redirect_to root_path
      end  
      # end
    rescue Conekta::ParameterValidationError => e
      #alguno de los parametros fueron invalidos
      puts e.message
    rescue Conekta::ProcessingError => e 
      # la tarjeta no pudo ser procesada, por ejemplo tarjeta declinada
      puts e.message
      redirect_to credit_pay_path, alert: "Tarjeta no pudo ser procesada, la tarjeta fue declinada, intenta nuevamente o con otra tarjeta."
    rescue Conekta::Error => e
      #un error ocurrió que no sucede en el flujo normal de cobros como por ejemplo un auth_key incorrecto
      redirect_to credit_pay_path, alert: "Tarjeta no pudo ser procesada, intenta nuevamente."  
      puts e.message
    
    end

  end

  def create_1
    @body_class = "cart"
    @total_kg = @cart.line_items.sum(:weight).to_i
    @subtotal = @cart.total_price_cart
    @ship_price = calculate_shipping_amount @total_kg
    @total = @ship_price + @subtotal

    order_sku = unique_id(@total)

    
    begin
      charge = Conekta::Charge.create({
        amount: (@total * 100),
        currency: "MXN",
        description: "Compra sotollantas",
        reference_id: "#{order_sku}",
        card: params[:conektaTokenId],
        details: {
          name: params[:charge][:name],
          email: current_user.email,
          phone: params[:charge][:phone_number],
          billing_address: {
            company_name: "n/a",
            street1: params[:charge][:full_address],
            city: params[:charge][:city],
            state: params[:charge][:state],
            zip: params[:charge][:zip_code],
            phone: params[:charge][:phone_number],
            email: current_user.email
          }
        }
        #"tok_a4Ff0dD2xYZZq82d9"
      })
      # @charge = Charge.new(charge_params)
      @charge = Charge.new(
          user_id: current_user.id.to_i,
          name: params[:charge][:name],
          full_address: params[:charge][:full_address],
          colonia: params[:charge][:colonia],
          city: params[:charge][:city],
          country: "México",
          state: params[:charge][:state],
          zip_code: params[:charge][:zip_code],
          phone_number: params[:charge][:phone_number],
          livemode: charge.livemode,
          conekta_status: charge.status,
          amount: @total,
          conekta_id: order_sku,
          payment_type: "Tarjeta de credito",
          delivery_service: "FedEx",
          currency: "MXN"
        )
      @charge.add_line_items_from_cart(@cart)
      @charge.line_items.each do |line_item|
        line_item.product.decrement!(:stock, line_item.quantity)
      end
      @charge.stock_discounted = true
      # @charge.save

      # respond_to do |f|
      if @charge.save

        AdminMailer.charge_paid(@charge).deliver
        AdminMailer.charge_paid_admin(@charge).deliver
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        # respond_with(@charge, location: show_charges_path(@charge))
        # f.html {redirect_to show_charges_path(@charge), notice: "pago procesado!"}

        redirect_to show_charge_path(@charge)
      else
        # f.html {redirect_to root_path, notice: "algo salio mal!"}
        redirect_to root_path
      end  
      # end
    rescue Conekta::ParameterValidationError => e
      #alguno de los parametros fueron invalidos
      puts e.message
    rescue Conekta::ProcessingError => e 

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/_cart_items.html.erb
<table class="responsive-table">
	<thead>
		<tr>
			<th></th>
			<th>nombre</th>
			<th>precio</th>
			<th>kg</th>
			<th>cantidad</th>
			<th>total</th>
		</tr>
	</thead>
	<tbody>
		<% @cart.line_items.each do |line| %>
			<tr>
        <%= hidden_field_tag 'product_ids[]', line.product.id %>
				<% unless line.product.galleries.empty? %>
					<td><%= image_tag line.product.galleries.first.photo.url(:small), size: "50" %></td>
				<% else %>
					<td><%= image_tag 'notire.svg', size: "50" %></td>
				<% end %>
				<td>
					<%= link_to show_product_path(line.product) do %>
						<%= line.product.title %>
					<% end %>
				</td>
				<td class="">
					$<%= line.product.price %>
				</td>
				<td><%= line.weight %> </td>
				
				<td>
	        <%= number_field_tag 'product_quantities[]', line.quantity, min: 1, max: 99 %>
				</td>
				<td class="price">$<%= line.total_price_line %> </td>
			</tr>
		<% end %>

	</tbody>
</table>

app/views/charges/_form2.html.erb
<%= form_for(@charge, url: oxxo_pay_path, html: {id: 'card-form2'}) do |f| %>
  <div class="col s12 border center-align">
    <h5>Total</h5>
    <p class="price2 center-align">$<%= final_price %> Mxn</p>
      <% if @charge.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@charge.errors.count, "error") %> prohibited this charge from being saved:</h2>

          <ul>
          <% @charge.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="input-field col s6">
        <%= f.text_field :name, required: true %>
        <%= f.label :name, 'nombre' %>
      </div>
      <div class="input-field col s6">
        <%= f.label :colonia, 'colonia' %>
        <%= f.text_field :colonia, required: true %>
      </div>
      <div class="input-field col s6">
        <%= f.label :city, 'ciudad' %>
        <%= f.text_field :city, required: true %>
      </div>
      
      <div class="input-field col s6">
        <%= f.label :state, 'estado' %>
        <%= f.text_field :state, required: true %>
      </div>
      <div class="input-field col s6">
        <%= f.label :zip_code, 'código postal' %>
        <%= f.number_field :zip_code, required: true %>
      </div>
      <div class="input-field col s6">
        <%= f.label :phone_number, 'número de teléfono' %>
        <%= f.number_field :phone_number, required: true %>
      </div>
      <div class="input-field col s12">
        <%= f.text_area :full_address, class: "materialize-textarea", required: true %>
        <%= f.label :full_address, 'direccion completa' %>
      </div>
      
      <div class="col s12">
      </div>
  </div>
  
    
  <%= f.button 'procesar pago', class: "btn" %>

<% end %>

app/views/charges/_ship_number.html.erb
<%= form_for(@charge) do |f| %>
<section class="">
  <div class="card-panel row">
  <div class="col s12">
      <h3>Detalles del cargo</h3>
      <p>
        <b>Producción?:</b>
        <% if @charge.livemode == "f" %>
          <span class="text-red">no</span>
        <% else %>
          <span class="text-green">si</span>
        <% end %>
      </p>
      <p>
        <b>Cantidad:</b>
        <span style="color: #27AB32; font-size:18px;">$ <%= @charge.amount %></span>
      </p>
      <p>
        <b>Moneda:</b>
        <%= @charge.currency %>
      </p>
      <p>
        <b>Tipo de cargo:</b>
        <%= @charge.payment_type %>
      </p>
      <p>
        <b>Código de referencia:</b>
        <%= @charge.conekta_id %>
      </p>
      <p>
        <b>Fecha de creación:</b>
        <%= local_time(@charge.created_at, '%m/%e/%y %I:%M%P') %>
      </p><br><br>

      <% if @charge.payment_type == "OXXO" %>
        <p>
          <%= image_tag(@charge.payment_bar_url) %><br>
          <%= @charge.payment_barcode %>
        </p><br><br>
      <% end %>
      <p>
        <b>Estado del pago:</b>
          <% if @charge.conekta_status == "paid" %>
            <span class="text-green">Pagado</span>
          <% elsif @charge.payment_type == "OXXO" %>
            <% if @charge.status == "enviado" or @charge.status == "listo_para_envio" or @charge.status == "pago_recibido" %>
              <span class="text-green">
                Pagado
              </span>
            <% else %>
              <span class="text-red"><%= @charge.conekta_status.humanize %></span>
            <% end %>
          <% end %>
      </p><br><br>
  </div>

      <div class="s12">
        <div class="col s8">
          <%= f.label :ship_number, 'número de rastreo' %>
          <%= f.text_field :ship_number, class: "" %>
        </div>
        <% unless @charge.ship_number.empty? %>
          <div class="col s4">
            <%= link_to 'Enviar numero de rastreo', charge_send_number_path(@charge), method: :put, class: "btn", data: { 
              confirm: @charge.counter >= 1 ? "Ya has enviado el número de rastreo #{@charge.counter} veces, estas seguro?" : "Enviar número de rastreo #{@charge.ship_number}" } %>
          </div>
        <% end %>
        
      </div>

      <div class="s12">
        
        <% if current_user.is? :admin and @charge.status == "enviado" %>
          <div class="col s12">
            <%= @charge.status %>
          </div>
        <% else %>
          <div class="col s12">
          <%= f.label :status, 'estado del envío' %>
            <%= f.select :status, Charge::Stages %>
          </div>
        <% end %>
      </div>


      
    </div>

    <div class="card-panel row">
      <h3>Detalles del envío</h3>
      <p>
        <b>País:</b>
        <%= @charge.country %>
      </p>
      <p>
        <b>Estado:</b>
        <%= @charge.state %>
      </p>
      <p>
        <b>Ciudad:</b>
        <%= @charge.city %>
      </p>
      <p>
        <b>Colonia:</b>
        <%= @charge.colonia %>
      </p>
      <p>
        <b>Código postal:</b>
        <%= @charge.zip_code %>
      </p>
      <p>
        <b>Direccion completa:</b>
        <%= @charge.full_address %>
      </p>
      <p>
        <b>Nombre envío:</b>
        <%= @charge.name %>
      </p>
      <p>
        <b>Telefono:</b>
        <%= @charge.phone_number %>
      </p>
      <p>
        <b>Servicio de envío:</b>
        <%= @charge.delivery_service %>
      </p>
    </div>
    <div class="card-panel row">
      <h3>Detalles del usuario</h3>
      <p>
        <b>Nombre:</b>
        <%= @charge.user.try(:name) %>
      </p>
      <p>
        <b>Email:</b>
        <%= @charge.user.try(:email) %>
      </p>
      
    </div>


     <div class="large-12 medium-12 small-12 center">
      <%= f.submit "actualizar", class: "btn expand" %>
     </div>



</section>
<% end %>


  

app/views/charges/cart_resume.html.erb
<%= render 'shared/navigation' %>


<div class="white cart-container">
	<div class="container">
		<div class="row">

		<% if @cart.line_items.empty? %>
			<div class="center-align">
				<br><br>
				<br><br>
				<br><br>
				<br><br>

				<h5>Tu carrito de compras esta vacío :(</h5>
				<%= link_to 'atras', root_path %>
				<br><br>
				<br><br>
				<br><br>
				<br><br>

			</div>
		<% else %>
			<div class="col s12 border" >
				<%= form_tag update_multiple_line_items_path, method: :put do %>
					<div class="col s12" id="cart-tableee">
							<%= render 'cart_items' %>
					</div>
					<div class="col s9">
						<%= submit_tag 'actualizar precios', class: "btn" %>
						<br><br>

					</div>
				<% end %>
				<div class="col s3">
					<%= link_to 'vaciar carrito', @cart, method: :delete, data: {confirm: '¿Estas seguro?'}, class: "btn red" %>
				</div>


			</div>

			<div class="col s12 right-align border">
				<h5>peso total del paquete</h5>
				<p><%= @total_kg %>Kg</p>
				<h5>subtotal</h5>
				<p class="price2">
					$<%= @subtotal %>
				</p>
				<h5>costo de envío</h5>
				<p class="price2">$<%= @ship_price %>*</p>
				<h3>Total</h3>
				<p class="price">$<%= @total %> Mxn</p>
				<p>* El costo de envio se calcula de la siguiente manera: $<%= SHIP_PRICE %> pesos por cada <%= KG_PACKAGE %> Kg.</p>

			</div>


				<div class="col s12 l6 pay-r ">
						<div class="border hoverable">
							<h4>Pagar con tarjeta de crédito o débito</h4>
							<%= image_tag 'cards.png', size: "300x45" %>
							<br><br>

							<%= form_tag(credit_pay_path) do %>
								<%= select_tag(:pay_option, options_for_select([['Pago a una sola exhibición', 1], ['3 Meses sin intereses +4.9%', 2], ['6 Meses sin intereses +7.9%', 3]]), class: "browser-default" ) %>
								<br>
								<%= submit_tag 'ir a pagar', class: "btn" %>
							<% end %>

							<p>*Paga hasta 6 meses in intereses</p>
						</div>
				</div>
				<div class="col s12 l6 pay-r">
						<div class="border hoverable">
							<h4>Pago en efectivo</h4>
							<%= image_tag 'logo-oxxo.png', size: "100x50" %>
							<br><br>
							<br><br>
							<% if @total > 10000 %>
								<%= link_to 'ir a pagar', '#', class: "btn disabled" %>
								<p style="color:red;">La cantidad máxima permitida para pagos en oxxo es de 10,000 pesos mexicanos.</p>
							<% else %>
								<%= link_to 'ir a pagar', oxxo_path, class: "btn"%>
							<% end %>
							<p>Pagos inmediatos</p>
						</div>
				</div>

			<div class="col s12 center-align" style="margin:2rem 0">
				<a href="#">Ver bancos participantes para pago con tarjeta de débito</a>

			</div>
		<% end %>



		</div>
	</div>
</div>

app/views/charges/index.html.erb
<%= render 'admin/nav' %>

<div class="container-2">

  <h1 class="">Ventas</h1>

<div class="row">
  <%= search_form_for(@st, url: charges_path, html:{class: "search-form"}) do |f| %>
      <div class="s12">
        <%= f.search_field :conekta_id_or_user_email_cont, {placeholder: "email o sku...", class: "form-control"} %>
      </div>
      <div class="col s9">
     
        <%= f.button 'buscar', class: "btn" %>
      </div>
      <div class="col s3">
        <%= link_to 'reestablecer', charges_path, class: "btn amber" %>
      </div>
  <% end %>
</div>

  <table class="striped centered">
    <thead>
      <tr>
        <th>Usuario</th>
        <th><%= sort_link(@st, :conekta_status, 'estado del pago') %></th>
        <th><%= sort_link(@st, :payment_type, 'Tipo de pago') %></th>
        <th><%= sort_link(@st, :status, 'Status del envio') %></th>
        <th><%= sort_link(@st, :counter, 'Rastreo enviado?') %></th>
        <th colspan="">Cargo</th>
        <th><%= sort_link(@st, :stock_discounted, 'Descontado de stock?') %></th>

        <th>Sku</th>
        <th><%= sort_link(@st, :created_at, 'Fecha') %></th>

        <th colspan="3"></th>

      </tr>
    </thead>

    <tbody>
      <% @charges.each do |charge| %>
        <tr>
          <td><%= charge.user.email %></td>
          <td><%= charge.conekta_status %></td>
          <td><%= charge.payment_type.humanize %></td>
          <td><%= charge.status %></td>
          <% if charge.counter >= 1 %>
            <td>
              <i class="material-icons g">done</i>
            </td>
          <% else %>
            <td>
              NO
            </td>
          <% end %>
          <td>$ <%= charge.amount %></td>
          <% if charge.stock_discounted %>
            <td>
              <i class="material-icons g">done</i>
            </td>
          <% else %>
            <td>
              NO
            </td>
          <% end %>
          <td><%= charge.conekta_id %></td>
          <td><%= local_time(charge.created_at) %></td>
          <td><%= link_to 'Editar', edit_charge_path(charge) %></td>
         
          <% if current_user.is? :super %>
            <td><%= link_to 'Destroy', charge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>

  </table>
  <%= will_paginate @charges, page_links: true, class: "text-center will-paginate pagination" %>


</div>

app/views/charges/new.html.erb
<h1>New Charge</h1>

<%= render 'form' %>

<%= link_to 'Back', charges_path %>

app/views/charges/show.html.erb
<%= render 'admin/nav' %>
<div class="container">
  <p>
    <strong>Name:</strong>
    <%= @charge.name %>
  </p>

  <p>
    <strong>Full address:</strong>
    <%= @charge.full_address %>
  </p>

  <p>
    <strong>Colonia:</strong>
    <%= @charge.colonia %>
  </p>

  <p>
    <strong>City:</strong>
    <%= @charge.city %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= @charge.country %>
  </p>

  <p>
    <strong>State:</strong>
    <%= @charge.state %>
  </p>

  <p>
    <strong>Zip code:</strong>
    <%= @charge.zip_code %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= @charge.phone_number %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @charge.status %>
  </p>

  <p>
    <strong>Ship number:</strong>
    <%= @charge.ship_number %>
  </p>

  <p>
    <strong>Delivery service:</strong>
    <%= @charge.delivery_service %>
  </p>

  <p>
    <strong>Conekta:</strong>
    <%= @charge.conekta_id %>
  </p>

  <p>
    <strong>Livemode:</strong>
    <%= @charge.livemode %>
  </p>

  <p>
    <strong>Conekta status:</strong>
    <%= @charge.conekta_status %>
  </p>
  <p>
    <strong>Amount:</strong>
    <%= @charge.amount %>
  </p>

  <p>
    <strong>Currency:</strong>
    <%= @charge.currency %>
  </p>

  <p>
    <strong>Payment type:</strong>
    <%= @charge.payment_type %>
  </p>

  <p>
    <strong>Payment barcode:</strong>
    <%= @charge.payment_barcode %>
  </p>

  <p>
    <strong>Payment bar url:</strong>
    <%= @charge.payment_bar_url %>
  </p>

  <p>
    <strong>User:</strong>
    <%= @charge.user %>
  </p>

  <p>
    <strong>Counter:</strong>
    <%= @charge.counter %>
  </p>

  <p>
    <strong>Stock discounted:</strong>
    <%= @charge.stock_discounted %>
  </p>

  <%= link_to 'Edit', edit_charge_path(@charge) %> |
  <%= link_to 'Back', charges_path %>
</div>